apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app-deploy
  labels:
    app: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: movie-app
      app: backend
  template:
    metadata:
      labels:
        name: movie-app
        app: backend
    spec:
      containers:
      - name: movie-app
        image: containers.cisco.com/hesiriki/movie-app:latest
